name: JSON file validation

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Validate successfully reproduced breaking update JSON
        uses: cardinalby/schema-validator-action@v3
        with:
          schema: "schemas/successful-reproduction-schemas/breaking-update.schema.json"
          file: "data/benchmark/*.json"
          refSchemasMap: 
            '{"https://github.com/chains-project/breaking-updates/blob/main/schemas/successful-reproduction-schemas/breaking-update-dependency.schema.json": "schemas/successful-reproduction-schemas/breaking-update-dependency.schema.json"}'

      - name: Validate not reproduced breaking update JSON
        uses: cardinalby/schema-validator-action@v3
        with:
          schema: "schemas/not-attempted-reproduction-schemas/breaking-update.schema.json"
          file: "data/not-reproduced-data/*.json"
          refSchemasMap:
            '{"https://github.com/chains-project/breaking-updates/blob/main/schemas/not-attempted-reproduction-schemas/breaking-update-dependency.schema.json": "schemas/not-attempted-reproduction-schemas/breaking-update-dependency.schema.json"}'

      - name: Validate reproduction failed breaking update JSON
        uses: cardinalby/schema-validator-action@v3
        with:
          schema: "schemas/unsuccessful-reproduction-schemas/breaking-update.schema.json"
          file: "data/unsuccessful-reproductions/*.json"
          refSchemasMap:
            '{"https://github.com/chains-project/breaking-updates/blob/main/schemas/unsuccessful-reproduction-schemas/breaking-update-dependency.schema.json": "schemas/unsuccessful-reproduction-schemas/breaking-update-dependency.schema.json"}'
